// lib/services/mock_leagues_data.dart - Mock Data 5 Top Liga Eropa

class MockLeaguesData {
  // Premier League
  static const List<Map<String, dynamic>> premierLeagueStandings = [
    {
      'position': 1,
      'team': {'name': 'Arsenal'},
      'playedGames': 38,
      'won': 26,
      'draw': 7,
      'lost': 5,
      'goalsFor': 71,
      'goalsAgainst': 27,
      'points': 85,
    },
    {
      'position': 2,
      'team': {'name': 'Manchester City'},
      'playedGames': 38,
      'won': 23,
      'draw': 9,
      'lost': 6,
      'goalsFor': 77,
      'goalsAgainst': 35,
      'points': 78,
    },
    {
      'position': 3,
      'team': {'name': 'Manchester United'},
      'playedGames': 38,
      'won': 20,
      'draw': 11,
      'lost': 7,
      'goalsFor': 69,
      'goalsAgainst': 50,
      'points': 71,
    },
    {
      'position': 4,
      'team': {'name': 'Aston Villa'},
      'playedGames': 38,
      'won': 19,
      'draw': 8,
      'lost': 11,
      'goalsFor': 56,
      'goalsAgainst': 49,
      'points': 65,
    },
    {
      'position': 5,
      'team': {'name': 'Liverpool'},
      'playedGames': 38,
      'won': 17,
      'draw': 9,
      'lost': 12,
      'goalsFor': 63,
      'goalsAgainst': 53,
      'points': 60,
    },
    {
      'position': 6,
      'team': {'name': 'Bournemouth'},
      'playedGames': 38,
      'won': 13,
      'draw': 18,
      'lost': 7,
      'goalsFor': 58,
      'goalsAgainst': 54,
      'points': 57,
    },
    {
      'position': 7,
      'team': {'name': 'Sunderland'},
      'playedGames': 38,
      'won': 14,
      'draw': 12,
      'lost': 12,
      'goalsFor': 42,
      'goalsAgainst': 48,
      'points': 54,
    },
    {
      'position': 8,
      'team': {'name': 'Brighton'},
      'playedGames': 38,
      'won': 14,
      'draw': 11,
      'lost': 13,
      'goalsFor': 52,
      'goalsAgainst': 46,
      'points': 53,
    },
    {
      'position': 9,
      'team': {'name': 'Brentford'},
      'playedGames': 38,
      'won': 14,
      'draw': 11,
      'lost': 13,
      'goalsFor': 55,
      'goalsAgainst': 52,
      'points': 53,
    },
    {
      'position': 10,
      'team': {'name': 'Chelsea'},
      'playedGames': 38,
      'won': 14,
      'draw': 10,
      'lost': 14,
      'goalsFor': 58,
      'goalsAgainst': 52,
      'points': 52,
    },
    {
      'position': 11,
      'team': {'name': 'Fulham'},
      'playedGames': 38,
      'won': 15,
      'draw': 7,
      'lost': 16,
      'goalsFor': 47,
      'goalsAgainst': 51,
      'points': 52,
    },
    {
      'position': 12,
      'team': {'name': 'Newcastle United'},
      'playedGames': 38,
      'won': 14,
      'draw': 7,
      'lost': 17,
      'goalsFor': 53,
      'goalsAgainst': 55,
      'points': 49,
    },
    {
      'position': 13,
      'team': {'name': 'Everton'},
      'playedGames': 38,
      'won': 13,
      'draw': 10,
      'lost': 15,
      'goalsFor': 47,
      'goalsAgainst': 50,
      'points': 49,
    },
    {
      'position': 14,
      'team': {'name': 'Leeds United'},
      'playedGames': 38,
      'won': 11,
      'draw': 14,
      'lost': 13,
      'goalsFor': 49,
      'goalsAgainst': 56,
      'points': 47,
    },
    {
      'position': 15,
      'team': {'name': 'Crystal Palace'},
      'playedGames': 38,
      'won': 11,
      'draw': 12,
      'lost': 15,
      'goalsFor': 41,
      'goalsAgainst': 51,
      'points': 45,
    },
    {
      'position': 16,
      'team': {'name': 'Nottingham Forest'},
      'playedGames': 38,
      'won': 11,
      'draw': 11,
      'lost': 16,
      'goalsFor': 48,
      'goalsAgainst': 51,
      'points': 44,
    },
    {
      'position': 17,
      'team': {'name': 'Tottenham Hotspur'},
      'playedGames': 38,
      'won': 10,
      'draw': 11,
      'lost': 17,
      'goalsFor': 48,
      'goalsAgainst': 57,
      'points': 41,
    },
    {
      'position': 18,
      'team': {'name': 'West Ham United'},
      'playedGames': 38,
      'won': 10,
      'draw': 9,
      'lost': 19,
      'goalsFor': 46,
      'goalsAgainst': 65,
      'points': 39,
    },
    {
      'position': 19,
      'team': {'name': 'Burnley'},
      'playedGames': 38,
      'won': 4,
      'draw': 10,
      'lost': 24,
      'goalsFor': 38,
      'goalsAgainst': 75,
      'points': 22,
    },
    {
      'position': 20,
      'team': {'name': 'Wolverhampton'},
      'playedGames': 38,
      'won': 3,
      'draw': 11,
      'lost': 24,
      'goalsFor': 27,
      'goalsAgainst': 68,
      'points': 20,
    },
  ];

  // La Liga (Spain)
  static const List<Map<String, dynamic>> laLigaStandings = [

    {
      'position': 1,
      'team': {'name': 'Barcelona'},
      'playedGames': 38,
      'won': 31,
      'draw': 1,
      'lost': 6,
      'goalsFor': 95,
      'goalsAgainst': 36,
      'goalDifference': 59,
      'points': 94,
    },
    {
      'position': 2,
      'team': {'name': 'Real Madrid'},
      'playedGames': 38,
      'won': 27,
      'draw': 5,
      'lost': 6,
      'goalsFor': 77,
      'goalsAgainst': 35,
      'goalDifference': 42,
      'points': 86,
    },
    {
      'position': 3,
      'team': {'name': 'Villarreal'},
      'playedGames': 38,
      'won': 22,
      'draw': 6,
      'lost': 10,
      'goalsFor': 72,
      'goalsAgainst': 46,
      'goalDifference': 26,
      'points': 72,
    },
    {
      'position': 4,
      'team': {'name': 'Atletico Madrid'},
      'playedGames': 38,
      'won': 21,
      'draw': 6,
      'lost': 11,
      'goalsFor': 62,
      'goalsAgainst': 44,
      'goalDifference': 18,
      'points': 69,
    },
    {
      'position': 5,
      'team': {'name': 'Real Betis'},
      'playedGames': 38,
      'won': 15,
      'draw': 15,
      'lost': 8,
      'goalsFor': 59,
      'goalsAgainst': 48,
      'goalDifference': 11,
      'points': 60,
    },
    {
      'position': 6,
      'team': {'name': 'Celta Vigo'},
      'playedGames': 38,
      'won': 14,
      'draw': 12,
      'lost': 12,
      'goalsFor': 53,
      'goalsAgainst': 48,
      'goalDifference': 5,
      'points': 54,
    },
    {
      'position': 7,
      'team': {'name': 'Getafe'},
      'playedGames': 38,
      'won': 15,
      'draw': 6,
      'lost': 17,
      'goalsFor': 32,
      'goalsAgainst': 38,
      'goalDifference': -6,
      'points': 51,
    },
    {
      'position': 8,
      'team': {'name': 'Rayo Vallecano'},
      'playedGames': 38,
      'won': 12,
      'draw': 14,
      'lost': 12,
      'goalsFor': 41,
      'goalsAgainst': 44,
      'goalDifference': -3,
      'points': 50,
    },
    {
      'position': 9,
      'team': {'name': 'Valencia'},
      'playedGames': 38,
      'won': 13,
      'draw': 10,
      'lost': 15,
      'goalsFor': 46,
      'goalsAgainst': 55,
      'goalDifference': -9,
      'points': 49,
    },
    {
      'position': 10,
      'team': {'name': 'Real Sociedad'},
      'playedGames': 38,
      'won': 11,
      'draw': 13,
      'lost': 14,
      'goalsFor': 59,
      'goalsAgainst': 61,
      'goalDifference': -2,
      'points': 46,
    },
    {
      'position': 11,
      'team': {'name': 'Espanyol'},
      'playedGames': 38,
      'won': 12,
      'draw': 10,
      'lost': 16,
      'goalsFor': 43,
      'goalsAgainst': 55,
      'goalDifference': -12,
      'points': 46,
    },
    {
      'position': 12,
      'team': {'name': 'Athletic Bilbao'},
      'playedGames': 38,
      'won': 13,
      'draw': 6,
      'lost': 19,
      'goalsFor': 43,
      'goalsAgainst': 58,
      'goalDifference': -15,
      'points': 45,
    },
    {
      'position': 13,
      'team': {'name': 'Sevilla'},
      'playedGames': 38,
      'won': 12,
      'draw': 7,
      'lost': 19,
      'goalsFor': 46,
      'goalsAgainst': 60,
      'goalDifference': -14,
      'points': 43,
    },
    {
      'position': 14,
      'team': {'name': 'Alaves'},
      'playedGames': 38,
      'won': 11,
      'draw': 10,
      'lost': 17,
      'goalsFor': 44,
      'goalsAgainst': 56,
      'goalDifference': -12,
      'points': 43,
    },
    {
      'position': 15,
      'team': {'name': 'Elche'},
      'playedGames': 38,
      'won': 10,
      'draw': 13,
      'lost': 15,
      'goalsFor': 49,
      'goalsAgainst': 57,
      'goalDifference': -8,
      'points': 43,
    },
    {
      'position': 16,
      'team': {'name': 'Levante'},
      'playedGames': 38,
      'won': 11,
      'draw': 9,
      'lost': 18,
      'goalsFor': 47,
      'goalsAgainst': 61,
      'goalDifference': -14,
      'points': 42,
    },
    {
      'position': 17,
      'team': {'name': 'Osasuna'},
      'playedGames': 38,
      'won': 11,
      'draw': 9,
      'lost': 18,
      'goalsFor': 44,
      'goalsAgainst': 50,
      'goalDifference': -6,
      'points': 42,
    },
    {
      'position': 18,
      'team': {'name': 'Mallorca'},
      'playedGames': 38,
      'won': 11,
      'draw': 9,
      'lost': 18,
      'goalsFor': 47,
      'goalsAgainst': 57,
      'goalDifference': -10,
      'points': 42,
    },
    {
      'position': 19,
      'team': {'name': 'Girona'},
      'playedGames': 38,
      'won': 9,
      'draw': 14,
      'lost': 15,
      'goalsFor': 39,
      'goalsAgainst': 55,
      'goalDifference': -16,
      'points': 41,
    },
    {
      'position': 20,
      'team': {'name': 'Real Oviedo'},
      'playedGames': 38,
      'won': 6,
      'draw': 11,
      'lost': 21,
      'goalsFor': 26,
      'goalsAgainst': 60,
      'goalDifference': -34,
      'points': 29,
    },
  ];

  // Serie A (Italy)
  static const List<Map<String, dynamic>> serieAStandings = [
    {
      'position': 1,
      'team': {'name': 'Inter'},
      'playedGames': 38,
      'won': 27,
      'draw': 6,
      'lost': 5,
      'goalsFor': 89,
      'goalsAgainst': 35,
      'goalDifference': 54,
      'points': 87,
    },
    {
      'position': 2,
      'team': {'name': 'Napoli'},
      'playedGames': 38,
      'won': 23,
      'draw': 7,
      'lost': 8,
      'goalsFor': 58,
      'goalsAgainst': 36,
      'goalDifference': 22,
      'points': 76,
    },
    {
      'position': 3,
      'team': {'name': 'Roma'},
      'playedGames': 38,
      'won': 23,
      'draw': 4,
      'lost': 11,
      'goalsFor': 59,
      'goalsAgainst': 31,
      'goalDifference': 28,
      'points': 73,
    },
    {
      'position': 4,
      'team': {'name': 'Como'},
      'playedGames': 38,
      'won': 20,
      'draw': 11,
      'lost': 7,
      'goalsFor': 65,
      'goalsAgainst': 29,
      'goalDifference': 36,
      'points': 71,
    },
    {
      'position': 5,
      'team': {'name': 'AC Milan'},
      'playedGames': 38,
      'won': 20,
      'draw': 10,
      'lost': 8,
      'goalsFor': 53,
      'goalsAgainst': 35,
      'goalDifference': 18,
      'points': 70,
    },
    {
      'position': 6,
      'team': {'name': 'Juventus'},
      'playedGames': 38,
      'won': 19,
      'draw': 12,
      'lost': 7,
      'goalsFor': 61,
      'goalsAgainst': 34,
      'goalDifference': 27,
      'points': 69,
    },
    {
      'position': 7,
      'team': {'name': 'Atalanta'},
      'playedGames': 38,
      'won': 15,
      'draw': 14,
      'lost': 9,
      'goalsFor': 51,
      'goalsAgainst': 36,
      'goalDifference': 15,
      'points': 59,
    },
    {
      'position': 8,
      'team': {'name': 'Bologna'},
      'playedGames': 38,
      'won': 16,
      'draw': 8,
      'lost': 14,
      'goalsFor': 49,
      'goalsAgainst': 46,
      'goalDifference': 3,
      'points': 56,
    },
    {
      'position': 9,
      'team': {'name': 'Lazio'},
      'playedGames': 38,
      'won': 14,
      'draw': 12,
      'lost': 12,
      'goalsFor': 41,
      'goalsAgainst': 40,
      'goalDifference': 1,
      'points': 54,
    },
    {
      'position': 10,
      'team': {'name': 'Udinese'},
      'playedGames': 38,
      'won': 14,
      'draw': 8,
      'lost': 16,
      'goalsFor': 45,
      'goalsAgainst': 48,
      'goalDifference': -3,
      'points': 50,
    },
    {
      'position': 11,
      'team': {'name': 'Sassuolo'},
      'playedGames': 38,
      'won': 14,
      'draw': 7,
      'lost': 17,
      'goalsFor': 46,
      'goalsAgainst': 50,
      'goalDifference': -4,
      'points': 49,
    },
    {
      'position': 12,
      'team': {'name': 'Torino'},
      'playedGames': 38,
      'won': 12,
      'draw': 9,
      'lost': 17,
      'goalsFor': 44,
      'goalsAgainst': 63,
      'goalDifference': -19,
      'points': 45,
    },
    {
      'position': 13,
      'team': {'name': 'Parma'},
      'playedGames': 38,
      'won': 11,
      'draw': 12,
      'lost': 15,
      'goalsFor': 28,
      'goalsAgainst': 46,
      'goalDifference': -18,
      'points': 45,
    },
    {
      'position': 14,
      'team': {'name': 'Cagliari'},
      'playedGames': 38,
      'won': 11,
      'draw': 10,
      'lost': 17,
      'goalsFor': 40,
      'goalsAgainst': 53,
      'goalDifference': -13,
      'points': 43,
    },
    {
      'position': 15,
      'team': {'name': 'Fiorentina'},
      'playedGames': 38,
      'won': 9,
      'draw': 15,
      'lost': 14,
      'goalsFor': 41,
      'goalsAgainst': 50,
      'goalDifference': -9,
      'points': 42,
    },
    {
      'position': 16,
      'team': {'name': 'Genoa'},
      'playedGames': 38,
      'won': 10,
      'draw': 11,
      'lost': 17,
      'goalsFor': 41,
      'goalsAgainst': 51,
      'goalDifference': -10,
      'points': 41,
    },
    {
      'position': 17,
      'team': {'name': 'Lecce'},
      'playedGames': 38,
      'won': 10,
      'draw': 8,
      'lost': 20,
      'goalsFor': 28,
      'goalsAgainst': 50,
      'goalDifference': -22,
      'points': 38,
    },
    {
      'position': 18,
      'team': {'name': 'Cremonese'},
      'playedGames': 38,
      'won': 8,
      'draw': 10,
      'lost': 20,
      'goalsFor': 32,
      'goalsAgainst': 57,
      'goalDifference': -25,
      'points': 34,
    },
    {
      'position': 19,
      'team': {'name': 'Verona'},
      'playedGames': 38,
      'won': 3,
      'draw': 12,
      'lost': 23,
      'goalsFor': 25,
      'goalsAgainst': 61,
      'goalDifference': -36,
      'points': 21,
    },
    {
      'position': 20,
      'team': {'name': 'Pisa'},
      'playedGames': 38,
      'won': 2,
      'draw': 12,
      'lost': 24,
      'goalsFor': 26,
      'goalsAgainst': 71,
      'goalDifference': -45,
      'points': 18,
    },
  ];

  // Bundesliga (Germany)
  static const List<Map<String, dynamic>> bundesligaStandings = [
    {
      'position': 1,
      'team': {'name': 'Bayern Munich'},
      'playedGames': 34,
      'won': 28,
      'draw': 5,
      'lost': 1,
      'goalsFor': 122,
      'goalsAgainst': 36,
      'goalDifference': 86,
      'points': 89,
    },
    {
      'position': 2,
      'team': {'name': 'Borussia Dortmund'},
      'playedGames': 34,
      'won': 22,
      'draw': 7,
      'lost': 5,
      'goalsFor': 70,
      'goalsAgainst': 34,
      'goalDifference': 36,
      'points': 73,
    },
    {
      'position': 3,
      'team': {'name': 'RB Leipzig'},
      'playedGames': 34,
      'won': 20,
      'draw': 5,
      'lost': 9,
      'goalsFor': 66,
      'goalsAgainst': 47,
      'goalDifference': 19,
      'points': 65,
    },
    {
      'position': 4,
      'team': {'name': 'VfB Stuttgart'},
      'playedGames': 34,
      'won': 18,
      'draw': 8,
      'lost': 8,
      'goalsFor': 71,
      'goalsAgainst': 49,
      'goalDifference': 22,
      'points': 62,
    },
    {
      'position': 5,
      'team': {'name': 'Hoffenheim'},
      'playedGames': 34,
      'won': 18,
      'draw': 7,
      'lost': 9,
      'goalsFor': 65,
      'goalsAgainst': 52,
      'goalDifference': 13,
      'points': 61,
    },
    {
      'position': 6,
      'team': {'name': 'Bayer Leverkusen'},
      'playedGames': 34,
      'won': 17,
      'draw': 8,
      'lost': 9,
      'goalsFor': 68,
      'goalsAgainst': 47,
      'goalDifference': 21,
      'points': 59,
    },
    {
      'position': 7,
      'team': {'name': 'SC Freiburg'},
      'playedGames': 34,
      'won': 13,
      'draw': 8,
      'lost': 13,
      'goalsFor': 51,
      'goalsAgainst': 57,
      'goalDifference': -6,
      'points': 47,
    },
    {
      'position': 8,
      'team': {'name': 'Eintracht Frankfurt'},
      'playedGames': 34,
      'won': 11,
      'draw': 11,
      'lost': 12,
      'goalsFor': 61,
      'goalsAgainst': 65,
      'goalDifference': -4,
      'points': 44,
    },
    {
      'position': 9,
      'team': {'name': 'FC Augsburg'},
      'playedGames': 34,
      'won': 12,
      'draw': 7,
      'lost': 15,
      'goalsFor': 45,
      'goalsAgainst': 61,
      'goalDifference': -16,
      'points': 43,
    },
    {
      'position': 10,
      'team': {'name': 'Mainz 05'},
      'playedGames': 34,
      'won': 10,
      'draw': 10,
      'lost': 14,
      'goalsFor': 44,
      'goalsAgainst': 53,
      'goalDifference': -9,
      'points': 40,
    },
    {
      'position': 11,
      'team': {'name': 'Union Berlin'},
      'playedGames': 34,
      'won': 10,
      'draw': 9,
      'lost': 15,
      'goalsFor': 44,
      'goalsAgainst': 58,
      'goalDifference': -14,
      'points': 39,
    },
    {
      'position': 12,
      'team': {'name': 'Borussia Monchengladbach'},
      'playedGames': 34,
      'won': 9,
      'draw': 11,
      'lost': 14,
      'goalsFor': 42,
      'goalsAgainst': 53,
      'goalDifference': -11,
      'points': 38,
    },
    {
      'position': 13,
      'team': {'name': 'Hamburger SV'},
      'playedGames': 34,
      'won': 9,
      'draw': 11,
      'lost': 14,
      'goalsFor': 40,
      'goalsAgainst': 54,
      'goalDifference': -14,
      'points': 38,
    },
    {
      'position': 14,
      'team': {'name': 'FC Koln'},
      'playedGames': 34,
      'won': 7,
      'draw': 11,
      'lost': 16,
      'goalsFor': 49,
      'goalsAgainst': 63,
      'goalDifference': -14,
      'points': 32,
    },
    {
      'position': 15,
      'team': {'name': 'Werder Bremen'},
      'playedGames': 34,
      'won': 8,
      'draw': 8,
      'lost': 18,
      'goalsFor': 37,
      'goalsAgainst': 60,
      'goalDifference': -23,
      'points': 32,
    },
    {
      'position': 16,
      'team': {'name': 'Wolfsburg'},
      'playedGames': 34,
      'won': 7,
      'draw': 8,
      'lost': 19,
      'goalsFor': 45,
      'goalsAgainst': 69,
      'goalDifference': -24,
      'points': 29,
    },
    {
      'position': 17,
      'team': {'name': 'Heidenheim'},
      'playedGames': 34,
      'won': 6,
      'draw': 8,
      'lost': 20,
      'goalsFor': 41,
      'goalsAgainst': 72,
      'goalDifference': -31,
      'points': 26,
    },
    {
      'position': 18,
      'team': {'name': 'St. Pauli'},
      'playedGames': 34,
      'won': 6,
      'draw': 8,
      'lost': 20,
      'goalsFor': 29,
      'goalsAgainst': 60,
      'goalDifference': -31,
      'points': 26,
    },
  ];

  // Ligue 1 (France)
  static const List<Map<String, dynamic>> ligue1Standings = [
    {
      'position': 1,
      'team': {'name': 'Paris Saint-Germain'},
      'playedGames': 34,
      'won': 24,
      'draw': 4,
      'lost': 6,
      'goalsFor': 74,
      'goalsAgainst': 29,
      'goalDifference': 45,
      'points': 76,
    },
    {
      'position': 2,
      'team': {'name': 'Lens'},
      'playedGames': 34,
      'won': 22,
      'draw': 4,
      'lost': 8,
      'goalsFor': 66,
      'goalsAgainst': 35,
      'goalDifference': 31,
      'points': 70,
    },
    {
      'position': 3,
      'team': {'name': 'Lille OSC'},
      'playedGames': 34,
      'won': 18,
      'draw': 7,
      'lost': 9,
      'goalsFor': 52,
      'goalsAgainst': 37,
      'goalDifference': 15,
      'points': 61,
    },
    {
      'position': 4,
      'team': {'name': 'Olympique Lyonnais'},
      'playedGames': 34,
      'won': 18,
      'draw': 6,
      'lost': 10,
      'goalsFor': 53,
      'goalsAgainst': 40,
      'goalDifference': 13,
      'points': 60,
    },
    {
      'position': 5,
      'team': {'name': 'Marseille'},
      'playedGames': 34,
      'won': 18,
      'draw': 5,
      'lost': 11,
      'goalsFor': 63,
      'goalsAgainst': 45,
      'goalDifference': 18,
      'points': 59,
    },
    {
      'position': 6,
      'team': {'name': 'Rennes'},
      'playedGames': 34,
      'won': 17,
      'draw': 8,
      'lost': 9,
      'goalsFor': 59,
      'goalsAgainst': 50,
      'goalDifference': 9,
      'points': 59,
    },
    {
      'position': 7,
      'team': {'name': 'Monaco'},
      'playedGames': 34,
      'won': 16,
      'draw': 6,
      'lost': 12,
      'goalsFor': 60,
      'goalsAgainst': 54,
      'goalDifference': 6,
      'points': 54,
    },
    {
      'position': 8,
      'team': {'name': 'Strasbourg'},
      'playedGames': 34,
      'won': 15,
      'draw': 8,
      'lost': 11,
      'goalsFor': 58,
      'goalsAgainst': 47,
      'goalDifference': 11,
      'points': 53,
    },
    {
      'position': 9,
      'team': {'name': 'Toulouse'},
      'playedGames': 34,
      'won': 12,
      'draw': 9,
      'lost': 13,
      'goalsFor': 47,
      'goalsAgainst': 46,
      'goalDifference': 1,
      'points': 45,
    },
    {
      'position': 10,
      'team': {'name': 'Lorient'},
      'playedGames': 34,
      'won': 11,
      'draw': 12,
      'lost': 11,
      'goalsFor': 48,
      'goalsAgainst': 51,
      'goalDifference': -3,
      'points': 45,
    },
    {
      'position': 11,
      'team': {'name': 'Paris FC'},
      'playedGames': 34,
      'won': 11,
      'draw': 11,
      'lost': 12,
      'goalsFor': 47,
      'goalsAgainst': 50,
      'goalDifference': -3,
      'points': 44,
    },
    {
      'position': 12,
      'team': {'name': 'Brest'},
      'playedGames': 34,
      'won': 10,
      'draw': 9,
      'lost': 15,
      'goalsFor': 43,
      'goalsAgainst': 55,
      'goalDifference': -12,
      'points': 39,
    },
    {
      'position': 13,
      'team': {'name': 'Angers'},
      'playedGames': 34,
      'won': 9,
      'draw': 9,
      'lost': 16,
      'goalsFor': 29,
      'goalsAgainst': 48,
      'goalDifference': -19,
      'points': 36,
    },
    {
      'position': 14,
      'team': {'name': 'Le Havre'},
      'playedGames': 34,
      'won': 7,
      'draw': 14,
      'lost': 13,
      'goalsFor': 32,
      'goalsAgainst': 44,
      'goalDifference': -12,
      'points': 35,
    },
    {
      'position': 15,
      'team': {'name': 'Auxerre'},
      'playedGames': 34,
      'won': 8,
      'draw': 10,
      'lost': 16,
      'goalsFor': 34,
      'goalsAgainst': 44,
      'goalDifference': -10,
      'points': 34,
    },
    {
      'position': 16,
      'team': {'name': 'Nice'},
      'playedGames': 34,
      'won': 7,
      'draw': 11,
      'lost': 16,
      'goalsFor': 37,
      'goalsAgainst': 60,
      'goalDifference': -23,
      'points': 32,
    },
    {
      'position': 17,
      'team': {'name': 'Nantes'},
      'playedGames': 34,
      'won': 5,
      'draw': 9,
      'lost': 20,
      'goalsFor': 29,
      'goalsAgainst': 52,
      'goalDifference': -23,
      'points': 24,
    },
    {
      'position': 18,
      'team': {'name': 'Metz'},
      'playedGames': 34,
      'won': 3,
      'draw': 8,
      'lost': 23,
      'goalsFor': 32,
      'goalsAgainst': 76,
      'goalDifference': -44,
      'points': 17,
    },
  ];

  /// Get standings berdasarkan league code
  static List<Map<String, dynamic>> getStandingsByLeague(String leagueCode) {
    switch (leagueCode) {
      case 'PL':
        return premierLeagueStandings;
      case 'PD':
        return laLigaStandings;
      case 'SA':
        return serieAStandings;
      case 'BL1':
        return bundesligaStandings;
      case 'FL1':
        return ligue1Standings;
      default:
        return premierLeagueStandings;
    }
  }
}
