// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMTvH14IeDlIV6l_yF5Ro62_c2TLwJaU',
    appId: '1:649289435052:web:b438f727f08ea4ea70dc09',
    messagingSenderId: '649289435052',
    projectId: 'ligakita-927d4',
    authDomain: 'ligakita-927d4.firebaseapp.com',
    storageBucket: 'ligakita-927d4.firebasestorage.app',
    measurementId: 'G-FHHSSP9HGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcOgnei5PDSNuXvzaT82opFreL8uhymbE',
    appId: '1:649289435052:android:7c57d76a006f48ed70dc09',
    messagingSenderId: '649289435052',
    projectId: 'ligakita-927d4',
    storageBucket: 'ligakita-927d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLsqRdAKXAqojW4kHyo8L8E90kX-y3K4',
    appId: '1:649289435052:ios:652f788f91c8072070dc09',
    messagingSenderId: '649289435052',
    projectId: 'ligakita-927d4',
    storageBucket: 'ligakita-927d4.firebasestorage.app',
    iosBundleId: 'com.example.ligakitaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLsqRdAKXAqojW4kHyo8L8E90kX-y3K4',
    appId: '1:649289435052:ios:652f788f91c8072070dc09',
    messagingSenderId: '649289435052',
    projectId: 'ligakita-927d4',
    storageBucket: 'ligakita-927d4.firebasestorage.app',
    iosBundleId: 'com.example.ligakitaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWMTvH14IeDlIV6l_yF5Ro62_c2TLwJaU',
    appId: '1:649289435052:web:e2f613d00ba5c3d570dc09',
    messagingSenderId: '649289435052',
    projectId: 'ligakita-927d4',
    authDomain: 'ligakita-927d4.firebaseapp.com',
    storageBucket: 'ligakita-927d4.firebasestorage.app',
    measurementId: 'G-QS0NQS00E2',
  );
}
